---
logs:
  level: LOG_LEVEL

database:
  path: 'DATABASE_PATH'
  sync: 'DATABASE_SYNC'

http:
  port: HTTP_PORT
  proxies: HTTP_PROXIES

encryption:
  keys:
    private: ENCRYPTION_PRIVATE
    public: ENCRYPTION_PUBLIC

jwt:
  secure: JWT_SECURE
  expire: JWT_EXPIRE
  keys:
    private: JWT_KEY_PRIVATE
    public: JWT_KEY_PUBLIC
