---
logs:
  level: http

database:
  path: /var/opt/echo
  sync: false

http:
  port: 3000
  proxies: 1

encryption:
  keys:
    private: /etc/opt/echo/encryption/private.key
    public: /etc/opt/echo/encryption/public.key

jwt:
  secure: false
  algorithm: RS256
  expire: 1296000000 # 15 days
  cookie: accessToken
  keys:
    private: /etc/opt/echo/jwt/private.key
    public: /etc/opt/echo/jwt/public.key

peer:
  path: http://localhost
